apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-universe-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: hello-universe
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1