apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    run: hello-universe
  name: hello-universe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-universe
    spec:
      containers:
        - name: hello-universe
          image: "jlandure/hello-universe:0.0.1"
          args:
            - "-http=0.0.0.0:80"
